### ISSUE TITLE
invalid memory address or nil pointer dereference on `overlaps`

### ISSUE THREAD

**Issue by bschaatsbergen** [bschaatsbergen/cidr#35]
When executing the following command:

```
$ cidr overlaps 10.0.14.0/22 10.0.0.0/16a
```

I seem to get the following error:

```
$ cidr overlaps 10.0.14.0/22 10.0.0.0/16a                                                                                                                                                  (base) 
ERRO[0000] invalid CIDR address: 10.0.0.0/16a           
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4abcbe]

goroutine 1 [running]:
github.com/bschaatsbergen/cidr/pkg/core.Overlaps(0xc000122900, 0x0)
        /home/runner/work/cidr/cidr/pkg/core/core.go:29 +0x1e
github.com/bschaatsbergen/cidr/cmd.overlaps(...)
        /home/runner/work/cidr/cidr/cmd/overlaps.go:36
github.com/bschaatsbergen/cidr/cmd.glob..func3(0x6dd3e0?, {0xc000148160, 0x2, 0x2?})
        /home/runner/work/cidr/cidr/cmd/overlaps.go:26 +0x165
github.com/spf13/cobra.(*Command).execute(0x6dd3e0, {0xc000148100, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x6dd660)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/bschaatsbergen/cidr/cmd.Execute()
        /home/runner/work/cidr/cidr/cmd/root.go:40 +0x25
main.main()
        /home/runner/work/cidr/cidr/main.go:6 +0x17
```

**Comment by bschaatsbergen** [comment]
Closing this issue, seems to be addressed in [v0.1.3](https://github.com/bschaatsbergen/cidr/releases/tag/v0.1.3).

```
$ cidr overlaps 10.0.14.0/22 10.0.0.0/16a
error: invalid CIDR address: 10.0.0.0/16a
See 'cidr overlaps -h' for help and examples
```
